version: "2.4"

services:
    frontend:
        build:
            context: .
            target: dev
        environment:
            - VITE_TITLE
            - VITE_API_URL
        volumes:
            - .:/app
        ports:
            - 8080:8080
