version: "2.4"

services:
  server:
    build:
      context: .
      target: dev
    env_file:
      - ./.env
    # environment:
    #   - API_BASE_PATH=/api
    volumes:
      - .:/app
    ports:
      - 8080:8080
