version: "2.4"

services:
  test:
    build:
      context: ./
      target: dev
    environment:
      - NODE_ENV=testing
    volumes:
      - .:/app
    command: "vue-cli-service test:unit"
    #command: "vue-cli-service test:unit && vue-cli-service test:e2e"
